backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  squash_merges: true
site_url: https://www.example.com
media_folder: static/assets
public_folder: assets
slug:
  encoding: "ascii"
  clean_accents: true

development_overrides:
  site_url: http://localhost:8000
  backend:
    name: file-system
    api_root: "http://localhost:8000/api"

collections:
  - label: "Menus"
    label_singular: "Menu"
    name: menus
    folder: src/content/cms/menus
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - name: title
      - name: links
        widget: list
        types:
          - name: link
            fields:
              - name: text
              - name: url

          - name: markdown
            fields:
              - name: title
              - { name: mdx, widget: markdown }

          - name: nested
            fields:
              - name: title
              - name: links
                widget: list
                fields:
                  - name: text
                  - { name: url, required: false }

          - name: button
            fields:
              - name: text
              - name: url

  - label: "Pages"
    label_singular: "Page"
    name: pages
    folder: src/content/cms/pages
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - name: title
      - { name: date, widget: date }
      - name: meta
        widget: object
        fields:
          - name: title
          - name: description
          - name: permalink
          - { name: ogImage, widget: image, default: /assets/og.png }
      - name: blocks
        widget: list
        types:
          - name: hero
            label: "Hero"
            fields:
              - name: kicker
                widget: object
                fields:
                  - name: url
                  - name: title
                  - name: body
                required: false
              - name: title
              - { name: subtitle, required: false }
              - { name: body, required: false }
              - name: buttons
                widget: list
                fields:
                  - name: title
                  - name: url
                  - name: look
                    widget: select
                    options: ["primary", "secondary"]
              - { name: image, widget: image, required: false }
              - { name: video, required: false }

          - name: sidekick
            label: "Sidekick"
            fields:
              - { name: icon, required: false }
              - name: title
              - { name: subtitle, required: false }
              - { name: image, widget: image, required: false }
              - name: layout
                widget: select
                options: ["left", "right"]
                default: left
              - name: blocks
                widget: list
                types:
                  - name: list
                    label: "List"
                    fields:
                      - name: list
                        widget: list
                        fields:
                          - { name: icon, required: false }
                          - { name: title, required: false }
                          - { name: body, required: false }
                          - { name: image, widget: image, required: false }
                      - name: layout
                        widget: select
                        options: ["list", "grid"]
                        default: list

                  - name: buttons
                    label: "Buttons"
                    fields:
                      - name: buttons
                        widget: list
                        fields:
                          - name: title
                          - name: url
                          - name: look
                            widget: select
                            options: ["primary", "secondary"]

                  - name: body
                    label: "Body"
                    widget: markdown

          - name: testimonials
            label: "Testimonials"
            fields:
              - { name: title, required: false }
              - { name: subtitle, required: false }
              - { name: body, required: false }
              - name: testimonials
                widget: list
                fields:
                  - name: name
                  - { name: position, required: false }
                  - { name: company, required: false }
                  - { name: testimonial, required: false }
                  - { name: image, widget: image, required: false }

          - name: logos
            label: "Logos"
            fields:
              - { name: title, required: false }
              - { name: subtitle, required: false }
              - { name: body, required: false }
              - name: logos
                widget: list
                fields:
                  - name: name
                  - name: url
                  - { name: image, widget: image }

          - name: pricing
            label: "Pricing"
            fields:
              - { name: title, required: false }
              - { name: subtitle, required: false }
              - { name: body, required: false }
              - name: pricing
                widget: list
                fields:
                  - name: title
                  - name: price
                    widget: object
                    fields:
                      - { name: monthly, widget: number }
                      - { name: yearly, widget: number }
                  - name: currency
                  - { name: mdx, widget: markdown, required: false }

  - label: "Posts"
    label_singular: "Blog post"
    name: posts
    folder: src/content/cms/posts
    create: true
    extension: mdx
    format: frontmatter
    fields:
      - name: title
      - { name: subtitle, required: false }
      - { name: date, widget: date }
      - name: meta
        widget: object
        fields:
          - name: title
          - name: description
          - name: permalink
          - { name: ogImage, widget: image }
      - { name: tags, required: false }
      - { name: highlighted, widget: boolean, default: false }
      - { name: body, widget: markdown }
